### PR TITLE
Rspec Test for Enumerable methods

### PR DESCRIPTION
**Pull request by garciajordy**
We did a test for the  Enumerable methods by using the Rspec framework.  we tested both positive and negative scenarios for the following enumerable methods:

- my_each
- my_each_with_index
- my_all?
- my_any?
- my_none?
- my_map
- my_count
- my_inject
- multiply_els

### CODE REVIEW

**Comment by elisha2kyakpo1** [comment]
#Invalid
Hello coders, I can see you have worked so hard, but something should be done.
Your project pull request doesn't have a professional title and summary comment. Make this change and submit another PR for review.

**Comment by Addis-Belete** [comment]
Thank you @elisha2kyakpo1 for your feedback. 
We fixed all feedbacks. so kindly review and approve it.

**Review by henatan99 — CHANGES_REQUESTED** [review]
# Changes Requested :recycle:
Hey Team, you have done great so far and implemented many of the test cases, yet you have missed some mandatory requirements. :clap: :clap:
You need to work on them before you project gets submitted. 

## To Highlight 
- Writes test cases for all the enumerable methods and spec tests pass
- Nice to make the required changes in the previous review 

## To Improve [MANDATORY] 
- Incorporate negative test scenarios in your test cases for each method (at least one for each)  because that is a MANDATORY requirement 

## OPTIONAL improvements 
- You can improve your repo to look more professional. You can work on the project description 
- You can add more representative test cases of the methods 
- 'require_relative' is preferred over 'require'

### Please, make the required changes and submit for re-review
### Happy Coding :computer: :mouse:

If you have any queries you can find me via:
- [LinedIn](https://www.linkedin.com/in/henok-mekonnen-2a251613/)
- [Twitter](https://twitter.com/henatan99)
- Henok Mekonnen on Slack

**Comment by mimipeshy** [comment]
#### STATUS: APPROVED :dancing_women: :partying_face:
Hello, team @garciajordy and @Addis0943   👋🏾 👋🏾 great job on this project. I like that you have incorporated negative test cases as pointed by the previous TSE. With that, I approve of this project. All the best in the next projects :technologist:
Regards
Peris Ndanu

**Pull request merged**
